### ISSUE TITLE
when adding new event via user, can't pick date

### ISSUE THREAD

**Issue by protesqu** [intelliants/subrion-plugin-events#5]
the date picker is just a blank popup

also, I can't see events waiting for approval

**Comment by 4unkur** [comment]
> the date picker is just a blank popup

Couldn't reproduce this. Datepicker works correctly.  
If you still face this problem, then please submit a ticket in our [HelpDesk](http://www.subrion.com/desk/). We will investigate and fix the issue.

> also, I can't see events waiting for approval

Events added by users from frontend are available in admin panel -> Extensions -> Events.  
You can change their statuses by clicking double clicking on `status` field and selecting `active` from the list. Then click anywhere except this field in order to save changes.
